language: c

compiler:
  - clang
  - gcc

script:
  - ./configure CFLAGS=-fsanitize=address LDFLAGS=-fsanitize=address
  - make bootstrap
  - make check-bootstrap

env:
  global:
    - ASAN_OPTIONS=detect_leaks=0

matrix:
  include:
    - os: linux
      arch: amd64
    - os: linux
      arch: i386
    #- os: linux
    #  arch: arm64
  include:
    - os: osx
    #osx_image: xcode8
      arch: amd64
    - os: osx
      arch: i386
    #- os: osx
    #  arch: arm64
